# Generated by Django 3.2.3 on 2021-06-06 07:17

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='no title', max_length=30, verbose_name='タイトル')),
                ('details', models.TextField(blank=True, max_length=1000, null=True, verbose_name='詳細')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='開始日')),
                ('start_time', models.TimeField(blank=True, default=datetime.datetime.now, verbose_name='開始時間')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'ordering': ['-start_date', '-start_time', '-created_at'],
            },
        ),
    ]
