# Generated by Django 3.2.3 on 2021-06-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tasks_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(default='no title', max_length=30, verbose_name='タイトル'),
        ),
    ]
